language: python
python:
  - '3.7'
sudo: false
install:
  - pip install -U platformio

env:
  - ENV=sonoff

script:
  - platformio run -e $ENV
before_deploy:
  - for file in .pioenvs/*/firmware.bin; do cp $file ${file%/*}.bin; done
